### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Alexdc-12** [linuxserver/docker-webgrabplus#22]
New custom license does not work with v3.0.0 it gets limited. Any chance of creating a beta tag for this docker?

**Comment by tobbenb** [comment]
A little bit more info would be nice, don't you think?

**Comment by Alexdc-12** [comment]
Hi
What more info would you like? 
V 3.0.0 is stable release. webgrabplus have changed their licenses recently and only the beta v 3.0.2 knows about these custom licenses. 
I run v3.0.3 on windows and its fine and recognises my license as a custom license. v 3.0.0 obviously doesnt know about custom licenses which is why i asked if you could create a beta tag to allow the consumers of the dockers to be able to chose whether to use the stable release or beta release. so you can have 

linuxserver/webgrabplus:latest

linuxserver/webgrabplus:beta

Let me know if you require more detail, its not an issue as such but more of a request.

Thanks

**Comment by tobbenb** [comment]
That's better. We can't know what you are thinking so we need information and we also don't follow the development of every app we have a container for.

As for creating a beta, I'll look into it. The issue with wg++ is that we have no way of knowing when there is a new release, so we have to check it manually.

**Comment by Alexdc-12** [comment]
Thanks, i can always let u know when a new version is released.

**Comment by Alexdc-12** [comment]
Hi
Webgrab have had to release an update due to security issues 
http://www.webgrabplus.com/content/release-v31

**Comment by EbenezumCZ** [comment]
> 
> 
> Hi
> Webgrab have had to release an update due to security issues
> http://www.webgrabplus.com/content/release-v31

Alexdc-12 is right. On top of that all versions below 3.1 stopped working.

**Comment by tobbenb** [comment]
I pushed a PR to update to version 3.1. If it checks out ok, it will get merged.

**Comment by Alexdc-12** [comment]
Im new to all this PR stuff, how long does the process take? I can see it was approved?

**Comment by tobbenb** [comment]
I was working and travelling yesterday, so didn't have time to merge it. Should be an updated container in an hour.

**Comment by Alexdc-12** [comment]
> I was working and travelling yesterday, so didn't have time to merge it. Should be an updated container in an hour.

Cheers pal! It wasnt a mian just do dnt know ehat the process was. Thanks for your help

**Comment by Alexdc-12** [comment]
Your gonna hate me! I updated and its still not working! 🙈

In the webgrab log i get the following error

[        ] WebGrab++ license request and update log
[        ] 2020/06/20 16:22
[        ] Job finished at 20/06/2020 16:22:02 done in 0s
[Critical] 
Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
[Critical] 
  at WG.common.azure.Azure_Access.  () [0x00016] in <e62b5ac7d0174b90acebaf12edcb2f39>:0 
  at WG.common.azure.Azure_Access..ctor () [0x00006] in <e62b5ac7d0174b90acebaf12edcb2f39>:0 
  at  .–..ctor (System.Collections.Generic.Dictionary`2[TKey,TValue] , System.Boolean , System.Boolean ) [0x004c2] in <896f87e576a8482c8f603908a14ec73f>:0 
  at  . ..ctor (System.String ) [0x012fb] in <896f87e576a8482c8f603908a14ec73f>:0 
  at  .―.  (System.String[] ) [0x00351] in <896f87e576a8482c8f603908a14ec73f>:0 
[Critical] Unhandled Exception
[Critical] For detailed info, see log file /config/WGLicense.log.txt
[Critical] Execution stopped

Can see others have had this issue with webgrab and the solution was to upgrade ubuntu or debian, is there a package that needs and update? 

http://www.webgrabplus.com/content/remote-server-returned-error-403-forbidden

**Comment by tobbenb** [comment]
We use the LTS version of Ubuntu as a base. Focal doesn't yet work in docker for arm, so we don't have a base image yet. So that means we are still on bionic.

I think the webgrab guys have to answer which app needs to be updated.

**Comment by Alexdc-12** [comment]
> We use the LTS version of Ubuntu as a base. Focal doesn't yet work in docker for arm, so we don't have a base image yet. So that means we are still on bionic. We have multi arch images for arm 32 and 64 bits and x86_64, so we can't leave the arm 32 bit hanging.
> 
> I think the webgrab guys have to answer which app needs to be updated.

A friend of mine looked at this issue. He installed mono-complete into the docker, updated the cron and restarted the docker and now it works

**Comment by tobbenb** [comment]
I'll look at it next week when I'm back home. 
Why does cron need to be updated?

**Comment by Alexdc-12** [comment]
Sorry thats out of context, he meant he updated the cron to set the time, then restarted docker

**Comment by fbacker** [comment]
I can confirm @Alexdc-12 that ```apt-get install mono-complete``` fixed the issue. Probably a smaller package is enough. 

http://webgrabplus.com/documentation/installation/linux

**Comment by tobbenb** [comment]
We are using the smaller version already, so then I guess we will have to use mono complete. 
Then we can still get this running until we have a focal base. That is good. 
I will push a fix on most likely Tuesday.

**Comment by fbacker** [comment]
@tobbenb did a test. Looks like you only need to add ```apt-get install libmono-system-net-http-webrequest4.0-cil```

**Comment by Alexdc-12** [comment]
> @tobbenb did a test. Looks like you only need to add `apt-get install libmono-system-net-http-webrequest4.0-cil`

Wish i read that a little while ago!

**Comment by tobbenb** [comment]
@fbacker Good find. Looks like I don't have to do anything now 😁
